/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 Jaecoo8-Model.glb --transform --keep-nodes Head_Light --output Jaecoo8-optimized-2.jsx 
Files: Jaecoo8-Model.glb [35.9MB] > /Users/saifullahakhtar/Desktop/Icon Development/jaecoo-car-showcase/public/optimized/Jaecoo8-Model-transformed.glb [2.69MB] (93%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/Jaecoo8-Model-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="J8_GRP" rotation={[Math.PI / 2, 0, 0]} scale={0.4}>
          <group name="Door_1_GRP" position={[1.903, 1.964, -1.608]}>
            <mesh name="Door_Body_Left_Front" geometry={nodes.Door_Body_Left_Front.geometry} material={materials.PaletteMaterial001} position={[-4.763, -4.922, 4]} />
            <group name="Door_Static_Left_Front" position={[-4.763, -4.922, 4]}>
              <mesh name="Mesh322" geometry={nodes.Mesh322.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Mesh322_1" geometry={nodes.Mesh322_1.geometry} material={materials.J8_Texture_5_SS} />
              <mesh name="Mesh322_2" geometry={nodes.Mesh322_2.geometry} material={materials.PaletteMaterial004} />
              <mesh name="Mesh322_3" geometry={nodes.Mesh322_3.geometry} material={materials.PaletteMaterial002} />
            </group>
          </group>
          <group name="Door_2_GRP" position={[-1.899, 1.964, -1.608]}>
            <mesh name="Door_Body_Right_Front" geometry={nodes.Door_Body_Right_Front.geometry} material={materials.PaletteMaterial001} position={[4.763, -4.922, 4]} />
            <group name="Door_Static_Right_Front" position={[4.763, -4.922, 4]}>
              <mesh name="Mesh344" geometry={nodes.Mesh344.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Mesh344_1" geometry={nodes.Mesh344_1.geometry} material={materials.PaletteMaterial004} />
              <mesh name="Mesh344_2" geometry={nodes.Mesh344_2.geometry} material={materials.J8_Texture_5_SS} />
              <mesh name="Mesh344_3" geometry={nodes.Mesh344_3.geometry} material={materials.PaletteMaterial002} />
            </group>
          </group>
          <group name="Door_3_GRP" position={[1.886, -0.169, -1.608]}>
            <mesh name="Door_Body_Left_Back" geometry={nodes.Door_Body_Left_Back.geometry} material={materials.PaletteMaterial001} position={[-4.72, 0.424, 4]} />
            <group name="Door_Static_Left_Back" position={[-4.72, 0.424, 4]}>
              <mesh name="Mesh361" geometry={nodes.Mesh361.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Mesh361_1" geometry={nodes.Mesh361_1.geometry} material={materials.PaletteMaterial004} />
              <mesh name="Mesh361_2" geometry={nodes.Mesh361_2.geometry} material={materials.J8_Texture_5_SS} />
              <mesh name="Mesh361_3" geometry={nodes.Mesh361_3.geometry} material={materials.PaletteMaterial002} />
            </group>
          </group>
          <group name="Door_4_GRP" position={[-1.881, -0.169, -1.608]}>
            <mesh name="Door_Body_Right_Back" geometry={nodes.Door_Body_Right_Back.geometry} material={materials.PaletteMaterial001} position={[4.72, 0.424, 4]} />
            <group name="Door_Static_Right_Back" position={[4.72, 0.424, 4]}>
              <mesh name="Mesh367" geometry={nodes.Mesh367.geometry} material={materials.PaletteMaterial004} />
              <mesh name="Mesh367_1" geometry={nodes.Mesh367_1.geometry} material={materials.J8_Texture_5_SS} />
              <mesh name="Mesh367_2" geometry={nodes.Mesh367_2.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Mesh367_3" geometry={nodes.Mesh367_3.geometry} material={materials.PaletteMaterial002} />
            </group>
          </group>
          <group name="Trunk_GRP" position={[0.002, -3.385, -3.245]}>
            <mesh name="Back_Light_Middle" geometry={nodes.Back_Light_Middle.geometry} material={materials.PaletteMaterial002} position={[0, 3.385, 3.233]} />
            <mesh name="Trunk_Body" geometry={nodes.Trunk_Body.geometry} material={materials.PaletteMaterial001} position={[0, 3.385, 3.233]} />
            <group name="Trunk_Static" position={[0, 3.385, 3.233]}>
              <mesh name="Mesh379" geometry={nodes.Mesh379.geometry} material={materials['J8_Plate_SS.001']} />
              <mesh name="Mesh379_1" geometry={nodes.Mesh379_1.geometry} material={materials.PaletteMaterial003} />
              <mesh name="Mesh379_2" geometry={nodes.Mesh379_2.geometry} material={materials.PaletteMaterial005} />
              <mesh name="Mesh379_3" geometry={nodes.Mesh379_3.geometry} material={materials.J8_Reflector_1_SS} />
              <mesh name="Mesh379_4" geometry={nodes.Mesh379_4.geometry} material={materials.PaletteMaterial004} />
            </group>
          </group>
        </group>
        <mesh name="Back_Light_Sides" geometry={nodes.Back_Light_Sides.geometry} material={materials.PaletteMaterial002} position={[0.001, 0.005, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.16} />
        <mesh name="Car_Body" geometry={nodes.Car_Body.geometry} material={materials.PaletteMaterial001} position={[0.001, 0.005, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.16} />
        <group name="Car_Static" position={[0.001, 0.005, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.16}>
          <mesh name="Mesh318" geometry={nodes.Mesh318.geometry} material={materials.J8_Texture_1_SS} />
          <mesh name="Mesh318_1" geometry={nodes.Mesh318_1.geometry} material={materials.PaletteMaterial005} />
          <mesh name="Mesh318_2" geometry={nodes.Mesh318_2.geometry} material={materials.J8_Texture_2_SS} />
          <mesh name="Mesh318_3" geometry={nodes.Mesh318_3.geometry} material={materials['J8_Plate_SS.001']} />
          <mesh name="Mesh318_4" geometry={nodes.Mesh318_4.geometry} material={materials.J8_Texture_4_SS} />
          <mesh name="Mesh318_5" geometry={nodes.Mesh318_5.geometry} material={materials.J8_Black_4_SS} />
          <mesh name="Mesh318_6" geometry={nodes.Mesh318_6.geometry} material={materials.J8_Texture_6_SS} />
          <mesh name="Mesh318_7" geometry={nodes.Mesh318_7.geometry} material={materials.J8_Texture_3_SS} />
          <mesh name="Mesh318_8" geometry={nodes.Mesh318_8.geometry} material={materials.PaletteMaterial003} />
          <mesh name="Mesh318_9" geometry={nodes.Mesh318_9.geometry} material={materials.PaletteMaterial004} />
          <mesh name="Mesh318_10" geometry={nodes.Mesh318_10.geometry} material={materials.PaletteMaterial006} />
        </group>
        <mesh name="Rear_Lights" geometry={nodes.Rear_Lights.geometry} material={materials.J8_Reflector_1_SS} position={[0.001, 0.005, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.16} />
        <mesh name="Wheel_1" geometry={nodes.Wheel_1.geometry} material={materials.PaletteMaterial007} rotation={[Math.PI / 2, 0, 0]} scale={0.4} />
      </group>
    </group>
  )
}

useGLTF.preload('/Jaecoo8-Model-transformed.glb')
