"use client";

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, SpotLight } from "@react-three/drei";
import * as THREE from "three";
import TransitionMaterial3 from "@/components/mesh-transition-material/MeshTransitionMaterial3";
import { useSnapshot } from "valtio";
import { state } from "@/lib/store";

export function Jaecoo8({ transitionColor, currentAnimation, ...props }) {
	const group = React.useRef();
	const { nodes, materials, animations } = useGLTF("/Jaecoo8-compressed.glb");
	const { actions, mixer } = useAnimations(animations, group);

	const { doorsOpen, trunkOpen, modelLights, camPosition, autoplayModel } =
		useSnapshot(state);

	// 1) Clone once, and set up transparency on both reflector and head-glass
	useEffect(() => {
		if (!group.current) return;

		const lightNames = [
			"JAECOO_J80007", // head-light glass
			"Mesh014", // head-light reflector
			"JAECOO_J80294001", // backlight 1
			"JAECOO_J80024001", // backlight 2
		];

		lightNames.forEach((n) => {
			const m = group.current.getObjectByName(n);
			if (!m) return;

			// clone the shared material
			m.material = m.material.clone();
			m.material.userData.isLightClone = true;

			// only on these two, enable transparency + additive glow
			if (n === "Mesh014" || n === "JAECOO_J80007") {
				m.material.transparent = true;
				m.material.depthWrite = false; // prevents z‐fighting with opaque geometry
				m.material.blending = THREE.AdditiveBlending;
				m.material.opacity = 0; // start fully off
			}
		});
	}, [nodes]);

	// 2) Toggle emissiveIntensity on all, and opacity on both reflector & head-glass
	useEffect(() => {
		if (!group.current) return;
		const intensityHead = modelLights ? 500 : 0;
		const intensityHeadGlass = modelLights ? 0.5 : 0;
		const intensityTail = modelLights ? 120 : 0;
		const alpha = modelLights ? 0.1 : 1;

		// helper to set emissive
		const setEmissive = (name, color, inten) => {
			const mesh = group.current.getObjectByName(name);
			if (!mesh?.material.userData.isLightClone) return;
			mesh.material.emissive.set(color);
			mesh.material.emissiveIntensity = inten;
		};

		// head glass + reflector
		setEmissive("JAECOO_J80007", "#ffffff", intensityHeadGlass);
		setEmissive("Mesh014", "#ffffff", intensityHead);
		// backlights
		setEmissive("JAECOO_J80294001", "#ff4f2b", intensityTail);
		setEmissive("JAECOO_J80024001", "#ff4f2b", intensityTail);

		// now drive opacity on the two transparent clones
		["JAECOO_J80007", "Mesh014"].forEach((n) => {
			const mesh = group.current.getObjectByName(n);
			if (mesh?.material.userData.isLightClone) {
				mesh.material.opacity = alpha;
			}
		});
	}, [modelLights]);

	// once actions object is ready, stash the clip names
	useEffect(() => {
		state.animationNames = Object.keys(actions);
	}, [actions]);

	// collect your door actions by name
	const doorActions = [
		actions["Door_1_GRPAction"],
		actions["Door_2_GRPAction"],
		actions["Door_3_GRPAction"],
		actions["Door_4_GRPAction"],
	].filter(Boolean); // filter out any that might be undefined

	const trunkActions = [
		actions["Trunk_GRP.001Action"], // Replace with the correct name of the trunk animation from the GLTF
	].filter(Boolean);

	// Doors
	useEffect(() => {
		if (!doorActions.length) return;
		const speed = 5.0;
		const direction = doorsOpen ? 1 : -1;
		const startTime = doorsOpen ? 0 : doorActions[0].getClip().duration;

		doorActions.forEach((action) => {
			action.reset();
			action.time = startTime;
			action.setLoop(THREE.LoopOnce, 1);
			action.clampWhenFinished = true;
			action.timeScale = speed * direction;
			action.play();
			action.onFinished = () => (action.paused = true);
		});
	}, [doorsOpen, actions]);

	// Trunk
	useEffect(() => {
		if (!trunkActions.length) return;
		const speed = 5.0;
		const direction = trunkOpen ? 1 : -1;
		const startTime = trunkOpen ? 0 : trunkActions[0].getClip().duration;

		trunkActions.forEach((action) => {
			action.reset();
			action.time = startTime;
			action.setLoop(THREE.LoopOnce, 1);
			action.clampWhenFinished = true;
			action.timeScale = speed * direction;
			action.play();
			action.onFinished = () => (action.paused = true);
		});
	}, [trunkOpen, actions]);

	// Spotlight
	const light = useRef();
	// useHelper(light, THREE.SpotLightHelper, "orange");

	const light2 = useRef();
	// useHelper(light2, THREE.SpotLightHelper, "orange");

	return (
		<>
			<group position={[0, 0, 0]}>
				<SpotLight
					ref={light}
					position={[0.7, 0.93, 1.9]} // Set starting position on the left side 1.85
					target-position={[0.7, 0.93, 1.9]}
					intensity={1}
					distance={15}
					angle={Math.PI / 10} // Adjust the angle (larger angle for a wider cone)
					penumbra={0}
					castShadow
					color={"#ffffff"}
					visible={modelLights}
					mapSize={[512, 512]}
					shadow-mapSize-width={1024}
					shadow-mapSize-height={1024}
					shadow-radius={8}
				/>

				<SpotLight
					ref={light2}
					position={[-0.7, 0.93, 1.9]} // Set starting position on the left side
					target-position={[-0.7, 0.93, 1.9]}
					intensity={1}
					distance={15}
					angle={Math.PI / 10} // Adjust the angle (larger angle for a wider cone)
					penumbra={0}
					castShadow
					color={"#ffffff"}
					visible={modelLights}
					mapSize={[512, 512]}
					shadow-mapSize-width={1024}
					shadow-mapSize-height={1024}
					shadow-radius={8}
				/>
			</group>

			<group ref={group} {...props} dispose={null}>
				<group name="Scene">
					<group
						name="J8_GRP"
						rotation={[Math.PI / 2, 0, 0]}
						scale={0.48}
					>
						<group name="Door_1_GRP" position={[1.9, 1.96, -1.61]}>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80252"
								geometry={nodes.JAECOO_J80252.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80253"
								geometry={nodes.JAECOO_J80253.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80254"
								geometry={nodes.JAECOO_J80254.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80255"
								geometry={nodes.JAECOO_J80255.geometry}
								material={materials.J8_Body_1_SS}
								position={[-4.76, -4.92, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								name="JAECOO_J80256001"
								geometry={nodes.JAECOO_J80256001.geometry}
								material={materials["J8_Mirror_SS.001"]}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80257001"
								geometry={nodes.JAECOO_J80257001.geometry}
								material={materials.J8_Black_1_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80258"
								geometry={nodes.JAECOO_J80258.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80259"
								geometry={nodes.JAECOO_J80259.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80260"
								geometry={nodes.JAECOO_J80260.geometry}
								material={materials.J8_Texture_5_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80261"
								geometry={nodes.JAECOO_J80261.geometry}
								material={materials.J8_Texture_5_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80262001"
								geometry={nodes.JAECOO_J80262001.geometry}
								material={materials["J8_Glass_1_SS.001"]}
								position={[-1.9, -1.96, 1.61]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80263001"
								geometry={nodes.JAECOO_J80263001.geometry}
								material={materials.J8_Body_1_SS}
								position={[-4.76, -4.92, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80264"
								geometry={nodes.JAECOO_J80264.geometry}
								material={materials.J8_Body_1_SS}
								position={[-4.76, -4.92, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80265"
								geometry={nodes.JAECOO_J80265.geometry}
								material={materials.J8_Black_1_SS}
								position={[-4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80266"
								geometry={nodes.JAECOO_J80266.geometry}
								material={materials.J8_Black_3_SS}
								position={[-4.76, -4.92, 4]}
							/>
						</group>
						<group name="Door_2_GRP" position={[-1.9, 1.96, -1.61]}>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80226"
								geometry={nodes.JAECOO_J80226.geometry}
								material={materials.J8_Black_1_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80227001"
								geometry={nodes.JAECOO_J80227001.geometry}
								material={materials.J8_Body_1_SS}
								position={[4.76, -4.92, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80228"
								geometry={nodes.JAECOO_J80228.geometry}
								material={materials.J8_Body_1_SS}
								position={[4.76, -4.92, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80229"
								geometry={nodes.JAECOO_J80229.geometry}
								material={materials.J8_Body_1_SS}
								position={[4.76, -4.92, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								name="JAECOO_J80230001"
								geometry={nodes.JAECOO_J80230001.geometry}
								material={materials["J8_Mirror_SS.001"]}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80231001"
								geometry={nodes.JAECOO_J80231001.geometry}
								material={materials["J8_Glass_1_SS.001"]}
								position={[1.9, -1.96, 1.61]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80232"
								geometry={nodes.JAECOO_J80232.geometry}
								material={materials.J8_Texture_5_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80233"
								geometry={nodes.JAECOO_J80233.geometry}
								material={materials.Chrome_1_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80234"
								geometry={nodes.JAECOO_J80234.geometry}
								material={materials.J8_Black_3_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80235"
								geometry={nodes.JAECOO_J80235.geometry}
								material={materials.Chrome_1_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80236001"
								geometry={nodes.JAECOO_J80236001.geometry}
								material={materials.J8_Black_1_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80237"
								geometry={nodes.JAECOO_J80237.geometry}
								material={materials.Chrome_1_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80238"
								geometry={nodes.JAECOO_J80238.geometry}
								material={materials.Chrome_1_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80239"
								geometry={nodes.JAECOO_J80239.geometry}
								material={materials.Chrome_1_SS}
								position={[4.76, -4.92, 4]}
							/>
							<mesh
								name="JAECOO_J80240"
								geometry={nodes.JAECOO_J80240.geometry}
								material={materials.J8_Interior_Light_SS}
								position={[4.76, -4.92, 4]}
							/>
						</group>
						<group
							name="Door_3_GRP"
							position={[1.89, -0.17, -1.61]}
						>
							<mesh
								name="JAECOO_J80268"
								geometry={nodes.JAECOO_J80268.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80269"
								geometry={nodes.JAECOO_J80269.geometry}
								material={materials.J8_Texture_5_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80270001"
								geometry={nodes.JAECOO_J80270001.geometry}
								material={materials.J8_Black_1_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80271001"
								geometry={nodes.JAECOO_J80271001.geometry}
								material={materials.J8_Body_1_SS}
								position={[-4.72, 0.42, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80272"
								geometry={nodes.JAECOO_J80272.geometry}
								material={materials.J8_Body_1_SS}
								position={[-4.72, 0.42, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								name="JAECOO_J80273001"
								geometry={nodes.JAECOO_J80273001.geometry}
								material={materials["J8_Glass_2_SS.001"]}
								position={[-1.89, 0.17, 1.61]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80274"
								geometry={nodes.JAECOO_J80274.geometry}
								material={materials.J8_Texture_5_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80275"
								geometry={nodes.JAECOO_J80275.geometry}
								material={materials.J8_Black_3_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80276"
								geometry={nodes.JAECOO_J80276.geometry}
								material={materials.J8_Texture_5_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								name="JAECOO_J80277"
								geometry={nodes.JAECOO_J80277.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								name="JAECOO_J80278"
								geometry={nodes.JAECOO_J80278.geometry}
								material={materials.Chrome_1_SS}
								position={[-4.72, 0.42, 4]}
							/>
							<mesh
								name="JAECOO_J80279"
								geometry={nodes.JAECOO_J80279.geometry}
								material={materials.J8_Interior_Light_SS}
								position={[-4.72, 0.42, 4]}
							/>
						</group>
						<group
							name="Door_4_GRP"
							position={[-1.88, -0.17, -1.61]}
						>
							<mesh
								name="JAECOO_J80241"
								geometry={nodes.JAECOO_J80241.geometry}
								material={materials.J8_Interior_Light_SS}
								position={[4.72, 0.42, 4]}
							/>
							<mesh
								name="JAECOO_J80242"
								geometry={nodes.JAECOO_J80242.geometry}
								material={materials.Chrome_1_SS}
								position={[4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80243"
								geometry={nodes.JAECOO_J80243.geometry}
								material={materials.J8_Texture_5_SS}
								position={[4.72, 0.42, 4]}
							/>
							<mesh
								name="JAECOO_J80244"
								geometry={nodes.JAECOO_J80244.geometry}
								material={materials.Chrome_1_SS}
								position={[4.72, 0.42, 4]}
							/>
							<mesh
								name="JAECOO_J80245"
								geometry={nodes.JAECOO_J80245.geometry}
								material={materials.Chrome_1_SS}
								position={[4.72, 0.42, 4]}
							/>
							<mesh
								name="JAECOO_J80246001"
								geometry={nodes.JAECOO_J80246001.geometry}
								material={materials["J8_Glass_2_SS.001"]}
								position={[1.88, 0.17, 1.61]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80247001"
								geometry={nodes.JAECOO_J80247001.geometry}
								material={materials.J8_Body_1_SS}
								position={[4.72, 0.42, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80248"
								geometry={nodes.JAECOO_J80248.geometry}
								material={materials.J8_Body_1_SS}
								position={[4.72, 0.42, 4]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80249"
								geometry={nodes.JAECOO_J80249.geometry}
								material={materials.J8_Black_3_SS}
								position={[4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80250"
								geometry={nodes.JAECOO_J80250.geometry}
								material={materials.J8_Texture_5_SS}
								position={[4.72, 0.42, 4]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80251001"
								geometry={nodes.JAECOO_J80251001.geometry}
								material={materials.J8_Black_1_SS}
								position={[4.72, 0.42, 4]}
							/>
						</group>
						<group name="Trunk_GRP" position={[0, -3.39, -3.25]}>
							<mesh
								name="JAECOO_J80280"
								geometry={nodes.JAECOO_J80280.geometry}
								material={materials.Chrome_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80281"
								geometry={nodes.JAECOO_J80281.geometry}
								material={materials.Chrome_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80282"
								geometry={nodes.JAECOO_J80282.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80283"
								geometry={nodes.JAECOO_J80283.geometry}
								material={materials.J8_Body_1_SS}
								position={[0, 3.39, 3.23]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80285"
								geometry={nodes.JAECOO_J80285.geometry}
								material={materials.J8_Body_2_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80286"
								geometry={nodes.JAECOO_J80286.geometry}
								material={materials["J8_Glass_2_SS.001"]}
								position={[0, 3.39, 3.25]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80287"
								geometry={nodes.JAECOO_J80287.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80288001"
								geometry={nodes.JAECOO_J80288001.geometry}
								material={materials.J8_Reflector_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80289"
								geometry={nodes.JAECOO_J80289.geometry}
								material={materials.J8_Body_1_SS}
								position={[0, 3.39, 3.23]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								name="JAECOO_J80290"
								geometry={nodes.JAECOO_J80290.geometry}
								material={materials.Chrome_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80291001"
								geometry={nodes.JAECOO_J80291001.geometry}
								material={materials.J8_Body_1_SS}
								position={[0, 3.39, 3.23]}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80292"
								geometry={nodes.JAECOO_J80292.geometry}
								material={materials.J8_Black_3_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80293001"
								geometry={nodes.JAECOO_J80293001.geometry}
								material={materials["J8_Glass_1_SS.001"]}
								position={[0, 3.39, 3.25]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80294001"
								geometry={nodes.JAECOO_J80294001.geometry}
								material={materials["J8_Red_Light_SS.001"]}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80295"
								geometry={nodes.JAECOO_J80295.geometry}
								material={materials["J8_Red_Light_SS.001"]}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80296"
								geometry={nodes.JAECOO_J80296.geometry}
								material={materials.J8_Body_2_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80297"
								geometry={nodes.JAECOO_J80297.geometry}
								material={materials.Chrome_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80298"
								geometry={nodes.JAECOO_J80298.geometry}
								material={materials.Chrome_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80299"
								geometry={nodes.JAECOO_J80299.geometry}
								material={materials.Chrome_2_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80300"
								geometry={nodes.JAECOO_J80300.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80301"
								geometry={nodes.JAECOO_J80301.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80302"
								geometry={nodes.JAECOO_J80302.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80303"
								geometry={nodes.JAECOO_J80303.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80304"
								geometry={nodes.JAECOO_J80304.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80305"
								geometry={nodes.JAECOO_J80305.geometry}
								material={materials.Chrome_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80306"
								geometry={nodes.JAECOO_J80306.geometry}
								material={materials.Chrome_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80307001"
								geometry={nodes.JAECOO_J80307001.geometry}
								material={materials.J8_Red_Logo_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80308001"
								geometry={nodes.JAECOO_J80308001.geometry}
								material={materials.J8_Black_1_SS}
								position={[0, 3.39, 3.23]}
							/>
							<mesh
								name="JAECOO_J80309001"
								geometry={nodes.JAECOO_J80309001.geometry}
								material={materials["J8_Plate_SS.001"]}
								position={[0, 3.39, 3.23]}
							/>
						</group>
						<group
							name="Rest_GRP001"
							position={[0, 0, -0.01]}
							scale={0.4}
						>
							<mesh
								name="JAECOO_J80001"
								geometry={nodes.JAECOO_J80001.geometry}
								material={materials["J8_Glass_1_SS.001"]}
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80002"
								geometry={nodes.JAECOO_J80002.geometry}
								material={materials.J8_Body_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80003"
								geometry={nodes.JAECOO_J80003.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80004"
								geometry={nodes.JAECOO_J80004.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80005"
								geometry={nodes.JAECOO_J80005.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								name="JAECOO_J80006"
								geometry={nodes.JAECOO_J80006.geometry}
								material={materials["J8_Glass_2_SS.001"]}
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							/>
							<mesh
								name="JAECOO_J80007"
								geometry={nodes.JAECOO_J80007.geometry}
								material={materials["J8_Glass_1_SS.001"]}
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							/>
							<group name="JAECOO_J80008001">
								<mesh
									name="Mesh014"
									geometry={nodes.Mesh014.geometry}
									material={
										materials["J8_White_Light_SS.001"]
									}
								/>
								<mesh
									castShadow
									receiveShadow
									name="Mesh014_1"
									geometry={nodes.Mesh014_1.geometry}
									material={materials.J8_Reflector_1_SS}
								/>
							</group>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80009001"
								geometry={nodes.JAECOO_J80009001.geometry}
								material={materials.J8_Black_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80010"
								geometry={nodes.JAECOO_J80010.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80011"
								geometry={nodes.JAECOO_J80011.geometry}
								material={materials.J8_Black_3_SS}
							/>
							<mesh
								name="JAECOO_J80012001"
								geometry={nodes.JAECOO_J80012001.geometry}
								material={materials.J8_LED_Vision_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80013"
								geometry={nodes.JAECOO_J80013.geometry}
								material={materials.J8_Black_3_SS}
							/>
							<mesh
								name="JAECOO_J80014"
								geometry={nodes.JAECOO_J80014.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80015"
								geometry={nodes.JAECOO_J80015.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80016"
								geometry={nodes.JAECOO_J80016.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80017"
								geometry={nodes.JAECOO_J80017.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80018"
								geometry={nodes.JAECOO_J80018.geometry}
								material={materials.J8_Texture_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80019"
								geometry={nodes.JAECOO_J80019.geometry}
								material={materials.J8_Texture_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80020"
								geometry={nodes.JAECOO_J80020.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								name="JAECOO_J80021"
								geometry={nodes.JAECOO_J80021.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80022001"
								geometry={nodes.JAECOO_J80022001.geometry}
								material={materials["J8_Glass_1_SS.001"]}
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80023"
								geometry={nodes.JAECOO_J80023.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80024001"
								geometry={nodes.JAECOO_J80024001.geometry}
								material={materials["J8_Red_Light_SS.001"]}
							/>
							<mesh
								name="JAECOO_J80025"
								geometry={nodes.JAECOO_J80025.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80026"
								geometry={nodes.JAECOO_J80026.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								name="JAECOO_J80027"
								geometry={nodes.JAECOO_J80027.geometry}
								material={materials.J8_LED_Vision_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80028"
								geometry={nodes.JAECOO_J80028.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80029001"
								geometry={nodes.JAECOO_J80029001.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80030"
								geometry={nodes.JAECOO_J80030.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80031"
								geometry={nodes.JAECOO_J80031.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80032"
								geometry={nodes.JAECOO_J80032.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80033"
								geometry={nodes.JAECOO_J80033.geometry}
								material={materials.J8_Body_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80034"
								geometry={nodes.JAECOO_J80034.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80035"
								geometry={nodes.JAECOO_J80035.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80036"
								geometry={nodes.JAECOO_J80036.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80037"
								geometry={nodes.JAECOO_J80037.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								name="JAECOO_J80038"
								geometry={nodes.JAECOO_J80038.geometry}
								material={materials["J8_Glass_2_SS.001"]}
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80039"
								geometry={nodes.JAECOO_J80039.geometry}
								material={materials["J8_Red_Light_SS.001"]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80040"
								geometry={nodes.JAECOO_J80040.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								name="JAECOO_J80041"
								geometry={nodes.JAECOO_J80041.geometry}
								material={materials.J8_Interior_Light_SS}
							/>
							<mesh
								name="JAECOO_J80042"
								geometry={nodes.JAECOO_J80042.geometry}
								material={materials["J8_Glass_2_SS.001"]}
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							/>
							<mesh
								name="JAECOO_J80043001"
								geometry={nodes.JAECOO_J80043001.geometry}
								material={materials["J8_Plate_SS.001"]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80044"
								geometry={nodes.JAECOO_J80044.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80045"
								geometry={nodes.JAECOO_J80045.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80046"
								geometry={nodes.JAECOO_J80046.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80047"
								geometry={nodes.JAECOO_J80047.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80048"
								geometry={nodes.JAECOO_J80048.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80049"
								geometry={nodes.JAECOO_J80049.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								name="JAECOO_J80050"
								geometry={nodes.JAECOO_J80050.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80051"
								geometry={nodes.JAECOO_J80051.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80052"
								geometry={nodes.JAECOO_J80052.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								name="JAECOO_J80053"
								geometry={nodes.JAECOO_J80053.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80054"
								geometry={nodes.JAECOO_J80054.geometry}
								material={materials.J8_Texture_4_SS}
							/>
							<mesh
								name="JAECOO_J80055"
								geometry={nodes.JAECOO_J80055.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80056"
								geometry={nodes.JAECOO_J80056.geometry}
								material={materials.J8_Black_4_SS}
							/>
							<mesh
								name="JAECOO_J80057"
								geometry={nodes.JAECOO_J80057.geometry}
								material={materials.Chrome_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80058"
								geometry={nodes.JAECOO_J80058.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80059"
								geometry={nodes.JAECOO_J80059.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80060"
								geometry={nodes.JAECOO_J80060.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80061"
								geometry={nodes.JAECOO_J80061.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80062"
								geometry={nodes.JAECOO_J80062.geometry}
								material={materials.J8_Black_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80063"
								geometry={nodes.JAECOO_J80063.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80064"
								geometry={nodes.JAECOO_J80064.geometry}
								material={materials.J8_Black_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80065"
								geometry={nodes.JAECOO_J80065.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80066"
								geometry={nodes.JAECOO_J80066.geometry}
								material={materials.J8_Texture_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80067"
								geometry={nodes.JAECOO_J80067.geometry}
								material={materials.J8_Texture_2_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80068"
								geometry={nodes.JAECOO_J80068.geometry}
								material={materials.J8_Texture_2_SS}
							/>
							<mesh
								name="JAECOO_J80069"
								geometry={nodes.JAECOO_J80069.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80070"
								geometry={nodes.JAECOO_J80070.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80071001"
								geometry={nodes.JAECOO_J80071001.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80072"
								geometry={nodes.JAECOO_J80072.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80073"
								geometry={nodes.JAECOO_J80073.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80074"
								geometry={nodes.JAECOO_J80074.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80075"
								geometry={nodes.JAECOO_J80075.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80076"
								geometry={nodes.JAECOO_J80076.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80077"
								geometry={nodes.JAECOO_J80077.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80078"
								geometry={nodes.JAECOO_J80078.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80079"
								geometry={nodes.JAECOO_J80079.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80080"
								geometry={nodes.JAECOO_J80080.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80081"
								geometry={nodes.JAECOO_J80081.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80082"
								geometry={nodes.JAECOO_J80082.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80083"
								geometry={nodes.JAECOO_J80083.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80084"
								geometry={nodes.JAECOO_J80084.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80085"
								geometry={nodes.JAECOO_J80085.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80086"
								geometry={nodes.JAECOO_J80086.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								name="JAECOO_J80087"
								geometry={nodes.JAECOO_J80087.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80088"
								geometry={nodes.JAECOO_J80088.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80089"
								geometry={nodes.JAECOO_J80089.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80090"
								geometry={nodes.JAECOO_J80090.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80091"
								geometry={nodes.JAECOO_J80091.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80092"
								geometry={nodes.JAECOO_J80092.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80093"
								geometry={nodes.JAECOO_J80093.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80094"
								geometry={nodes.JAECOO_J80094.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80095"
								geometry={nodes.JAECOO_J80095.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80096"
								geometry={nodes.JAECOO_J80096.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80097"
								geometry={nodes.JAECOO_J80097.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80098"
								geometry={nodes.JAECOO_J80098.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80099"
								geometry={nodes.JAECOO_J80099.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80100"
								geometry={nodes.JAECOO_J80100.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80101"
								geometry={nodes.JAECOO_J80101.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80102"
								geometry={nodes.JAECOO_J80102.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80103"
								geometry={nodes.JAECOO_J80103.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80104"
								geometry={nodes.JAECOO_J80104.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80105"
								geometry={nodes.JAECOO_J80105.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80106"
								geometry={nodes.JAECOO_J80106.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80107"
								geometry={nodes.JAECOO_J80107.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80108"
								geometry={nodes.JAECOO_J80108.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80109"
								geometry={nodes.JAECOO_J80109.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80110"
								geometry={nodes.JAECOO_J80110.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80111"
								geometry={nodes.JAECOO_J80111.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80112"
								geometry={nodes.JAECOO_J80112.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80113"
								geometry={nodes.JAECOO_J80113.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80114"
								geometry={nodes.JAECOO_J80114.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80115"
								geometry={nodes.JAECOO_J80115.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80116"
								geometry={nodes.JAECOO_J80116.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80117"
								geometry={nodes.JAECOO_J80117.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80118"
								geometry={nodes.JAECOO_J80118.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80119"
								geometry={nodes.JAECOO_J80119.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80120"
								geometry={nodes.JAECOO_J80120.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80121"
								geometry={nodes.JAECOO_J80121.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80122"
								geometry={nodes.JAECOO_J80122.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80123"
								geometry={nodes.JAECOO_J80123.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80124"
								geometry={nodes.JAECOO_J80124.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80125"
								geometry={nodes.JAECOO_J80125.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80126"
								geometry={nodes.JAECOO_J80126.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80127"
								geometry={nodes.JAECOO_J80127.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80128"
								geometry={nodes.JAECOO_J80128.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80129"
								geometry={nodes.JAECOO_J80129.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80130"
								geometry={nodes.JAECOO_J80130.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80131"
								geometry={nodes.JAECOO_J80131.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80132"
								geometry={nodes.JAECOO_J80132.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80133"
								geometry={nodes.JAECOO_J80133.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80134"
								geometry={nodes.JAECOO_J80134.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80135"
								geometry={nodes.JAECOO_J80135.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80136"
								geometry={nodes.JAECOO_J80136.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80137"
								geometry={nodes.JAECOO_J80137.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80138"
								geometry={nodes.JAECOO_J80138.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80139"
								geometry={nodes.JAECOO_J80139.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80140"
								geometry={nodes.JAECOO_J80140.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80141"
								geometry={nodes.JAECOO_J80141.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80142"
								geometry={nodes.JAECOO_J80142.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80143"
								geometry={nodes.JAECOO_J80143.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80144"
								geometry={nodes.JAECOO_J80144.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80145"
								geometry={nodes.JAECOO_J80145.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80146"
								geometry={nodes.JAECOO_J80146.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80147"
								geometry={nodes.JAECOO_J80147.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80148"
								geometry={nodes.JAECOO_J80148.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80149"
								geometry={nodes.JAECOO_J80149.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80150"
								geometry={nodes.JAECOO_J80150.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80151"
								geometry={nodes.JAECOO_J80151.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80152"
								geometry={nodes.JAECOO_J80152.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80153"
								geometry={nodes.JAECOO_J80153.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80154"
								geometry={nodes.JAECOO_J80154.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80155"
								geometry={nodes.JAECOO_J80155.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80156"
								geometry={nodes.JAECOO_J80156.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80157"
								geometry={nodes.JAECOO_J80157.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80158"
								geometry={nodes.JAECOO_J80158.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80159"
								geometry={nodes.JAECOO_J80159.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80160"
								geometry={nodes.JAECOO_J80160.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80161"
								geometry={nodes.JAECOO_J80161.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80162"
								geometry={nodes.JAECOO_J80162.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80163"
								geometry={nodes.JAECOO_J80163.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80164"
								geometry={nodes.JAECOO_J80164.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80165"
								geometry={nodes.JAECOO_J80165.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80166"
								geometry={nodes.JAECOO_J80166.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80167"
								geometry={nodes.JAECOO_J80167.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80168"
								geometry={nodes.JAECOO_J80168.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80169"
								geometry={nodes.JAECOO_J80169.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80170"
								geometry={nodes.JAECOO_J80170.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80171"
								geometry={nodes.JAECOO_J80171.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80172"
								geometry={nodes.JAECOO_J80172.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80173"
								geometry={nodes.JAECOO_J80173.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80174"
								geometry={nodes.JAECOO_J80174.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80175"
								geometry={nodes.JAECOO_J80175.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80176"
								geometry={nodes.JAECOO_J80176.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80177"
								geometry={nodes.JAECOO_J80177.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80178"
								geometry={nodes.JAECOO_J80178.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80179"
								geometry={nodes.JAECOO_J80179.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80180"
								geometry={nodes.JAECOO_J80180.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80181"
								geometry={nodes.JAECOO_J80181.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80182"
								geometry={nodes.JAECOO_J80182.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80183"
								geometry={nodes.JAECOO_J80183.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80184"
								geometry={nodes.JAECOO_J80184.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80185"
								geometry={nodes.JAECOO_J80185.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80186"
								geometry={nodes.JAECOO_J80186.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80187"
								geometry={nodes.JAECOO_J80187.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80188"
								geometry={nodes.JAECOO_J80188.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80189"
								geometry={nodes.JAECOO_J80189.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80190"
								geometry={nodes.JAECOO_J80190.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80191"
								geometry={nodes.JAECOO_J80191.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80192"
								geometry={nodes.JAECOO_J80192.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80193"
								geometry={nodes.JAECOO_J80193.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80194"
								geometry={nodes.JAECOO_J80194.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80195"
								geometry={nodes.JAECOO_J80195.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80196"
								geometry={nodes.JAECOO_J80196.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80197"
								geometry={nodes.JAECOO_J80197.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80198"
								geometry={nodes.JAECOO_J80198.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80199"
								geometry={nodes.JAECOO_J80199.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80200"
								geometry={nodes.JAECOO_J80200.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80201"
								geometry={nodes.JAECOO_J80201.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80202"
								geometry={nodes.JAECOO_J80202.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80203"
								geometry={nodes.JAECOO_J80203.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80204"
								geometry={nodes.JAECOO_J80204.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80205"
								geometry={nodes.JAECOO_J80205.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80206"
								geometry={nodes.JAECOO_J80206.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80207"
								geometry={nodes.JAECOO_J80207.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80208"
								geometry={nodes.JAECOO_J80208.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								name="JAECOO_J80209"
								geometry={nodes.JAECOO_J80209.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80210"
								geometry={nodes.JAECOO_J80210.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80211"
								geometry={nodes.JAECOO_J80211.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80212"
								geometry={nodes.JAECOO_J80212.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								name="JAECOO_J80213"
								geometry={nodes.JAECOO_J80213.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80214"
								geometry={nodes.JAECOO_J80214.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80215"
								geometry={nodes.JAECOO_J80215.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80216"
								geometry={nodes.JAECOO_J80216.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80217"
								geometry={nodes.JAECOO_J80217.geometry}
								material={materials.Chrome_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80218"
								geometry={nodes.JAECOO_J80218.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80219"
								geometry={nodes.JAECOO_J80219.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80220"
								geometry={nodes.JAECOO_J80220.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80221"
								geometry={nodes.JAECOO_J80221.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80222"
								geometry={nodes.JAECOO_J80222.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								name="JAECOO_J80223001"
								geometry={nodes.JAECOO_J80223001.geometry}
								material={materials["J8_Mirror_SS.001"]}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80224"
								geometry={nodes.JAECOO_J80224.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80225"
								geometry={nodes.JAECOO_J80225.geometry}
								material={materials.J8_Interior_Black_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80284"
								geometry={nodes.JAECOO_J80284.geometry}
								material={materials.J8_Body_1_SS}
							>
								<TransitionMaterial3
									roughness={0.38}
									metalness={1}
									clearcoat={0.9}
									clearcoatRoughness={0.1}
									transitionTime={0.4}
									transitionColor={transitionColor}
								/>
							</mesh>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80310"
								geometry={nodes.JAECOO_J80310.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								name="JAECOO_J80311"
								geometry={nodes.JAECOO_J80311.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80312"
								geometry={nodes.JAECOO_J80312.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80313"
								geometry={nodes.JAECOO_J80313.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80314001"
								geometry={nodes.JAECOO_J80314001.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80315001"
								geometry={nodes.JAECOO_J80315001.geometry}
								material={materials.J8_Brake_Discs_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80316001"
								geometry={nodes.JAECOO_J80316001.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80317"
								geometry={nodes.JAECOO_J80317.geometry}
								material={materials.Chrome_3_SS}
							/>
							<group
								name="JAECOO_J80318001"
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							>
								<mesh
									castShadow
									receiveShadow
									name="Mesh411"
									geometry={nodes.Mesh411.geometry}
									material={materials["J8_Tire_2_SS.002"]}
								/>
								<mesh
									castShadow
									receiveShadow
									name="Mesh411_1"
									geometry={nodes.Mesh411_1.geometry}
									material={materials["J8_Tire_1_SS.002"]}
								/>
							</group>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80319"
								geometry={nodes.JAECOO_J80319.geometry}
								material={materials.J8_Brake_Discs_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80320"
								geometry={nodes.JAECOO_J80320.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80321001"
								geometry={nodes.JAECOO_J80321001.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<group
								name="JAECOO_J80322001"
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							>
								<mesh
									castShadow
									receiveShadow
									name="Mesh410"
									geometry={nodes.Mesh410.geometry}
									material={materials["J8_Tire_2_SS.002"]}
								/>
								<mesh
									castShadow
									receiveShadow
									name="Mesh410_1"
									geometry={nodes.Mesh410_1.geometry}
									material={materials["J8_Tire_1_SS.002"]}
								/>
							</group>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80323001"
								geometry={nodes.JAECOO_J80323001.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80324001"
								geometry={nodes.JAECOO_J80324001.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80325"
								geometry={nodes.JAECOO_J80325.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80326"
								geometry={nodes.JAECOO_J80326.geometry}
								material={materials.J8_Brake_Discs_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80327001"
								geometry={nodes.JAECOO_J80327001.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80328"
								geometry={nodes.JAECOO_J80328.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<group
								name="JAECOO_J80329001"
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							>
								<mesh
									castShadow
									receiveShadow
									name="Mesh408"
									geometry={nodes.Mesh408.geometry}
									material={materials["J8_Tire_2_SS.002"]}
								/>
								<mesh
									castShadow
									receiveShadow
									name="Mesh408_1"
									geometry={nodes.Mesh408_1.geometry}
									material={materials["J8_Tire_1_SS.002"]}
								/>
							</group>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80330"
								geometry={nodes.JAECOO_J80330.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80331001"
								geometry={nodes.JAECOO_J80331001.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80332001"
								geometry={nodes.JAECOO_J80332001.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80333"
								geometry={nodes.JAECOO_J80333.geometry}
								material={materials.J8_Brake_Discs_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80334001"
								geometry={nodes.JAECOO_J80334001.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80335"
								geometry={nodes.JAECOO_J80335.geometry}
								material={materials.J8_Brakes_SS}
							/>
							<group
								name="JAECOO_J80336001"
								position={[-0.01, 0, 0.03]}
								scale={2.51}
							>
								<mesh
									castShadow
									receiveShadow
									name="Mesh409"
									geometry={nodes.Mesh409.geometry}
									material={materials["J8_Tire_2_SS.002"]}
								/>
								<mesh
									castShadow
									receiveShadow
									name="Mesh409_1"
									geometry={nodes.Mesh409_1.geometry}
									material={materials["J8_Tire_1_SS.002"]}
								/>
							</group>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80337"
								geometry={nodes.JAECOO_J80337.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80338001"
								geometry={nodes.JAECOO_J80338001.geometry}
								material={materials.J8_Black_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80339001"
								geometry={nodes.JAECOO_J80339001.geometry}
								material={materials.Chrome_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80340"
								geometry={nodes.JAECOO_J80340.geometry}
								material={materials.J8_Texture_6_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80341"
								geometry={nodes.JAECOO_J80341.geometry}
								material={materials.J8_Texture_6_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80342"
								geometry={nodes.JAECOO_J80342.geometry}
								material={materials.J8_Texture_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80343"
								geometry={nodes.JAECOO_J80343.geometry}
								material={materials.J8_Steering_Wheel_SS}
							/>
							<mesh
								name="JAECOO_J80344"
								geometry={nodes.JAECOO_J80344.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80345"
								geometry={nodes.JAECOO_J80345.geometry}
								material={materials.J8_Texture_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80346"
								geometry={nodes.JAECOO_J80346.geometry}
								material={materials.J8_Texture_3_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80347"
								geometry={nodes.JAECOO_J80347.geometry}
								material={materials.J8_Black_4_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80348"
								geometry={nodes.JAECOO_J80348.geometry}
								material={materials.J8_Interior_Black_SS}
							/>
							<mesh
								name="JAECOO_J80349"
								geometry={nodes.JAECOO_J80349.geometry}
								material={materials.Chrome_1_SS}
							/>
							<mesh
								castShadow
								receiveShadow
								name="JAECOO_J80350"
								geometry={nodes.JAECOO_J80350.geometry}
								material={materials.J8_Texture_1_SS}
							/>
						</group>
					</group>
				</group>
			</group>
		</>
	);
}

useGLTF.preload("/Jaecoo8-compressed.glb");
